### PR TITLE
html is now styled

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by TimPietrusky** [comment]
Wow that's awesome! Thank you very much!

**Comment by Haroenv** [comment]
Is there a reason why there is no gh-pages branch?

**Comment by LukyVj** [comment]
@Haroenv I guess we just doesn't need it :)

**Comment by reimersjan** [comment]
discuss here https://github.com/bullgit/bullshit-job-titles/issues/16

**Pull request merged**
